### PR TITLE
Added Trac Converter

### PR DESCRIPTION
**Pull request by Rednox**
Hey, I just added the converter for trac. Can you please add that to the page?

### CODE REVIEW

**Comment by thdoan** [comment]
@Rednox There is already a Wiki format -- is that supported by Trac?

FYI, I merged your PR on a test branch, but my minifier is throwing an error around line 468 in DataGridRenderer.js. Also, the Markdown option no longer works.

**Comment by Rednox** [comment]
@thdoan I didn't get the wiki format running with trac. It is also not in the documentation of trac. I fixed the problem with Markdown in the DataGridRenderer.

**Comment by thdoan** [comment]
@Rednox In Trac, are the number columns right-aligned? According to their docs (https://trac.edgewall.org/wiki/WikiFormatting#Tables), the text has to touch `||` on the right edge for it to be right-aligned. If it isn't right-aligned, then I'll add this patch as well.

**Comment by thdoan** [comment]
@Rednox FYI I've updated the Trac formatting code to adhere to [Trac specs](https://trac.edgewall.org/wiki/WikiFormatting#Tables) for column headers and right alignment of numeric columns. New output for sample data:

```
||= NAME =||= VALUE =||= COLOR =||= DATE =||
|| Alan || 12|| blue || Sep. 25, 2009 ||
|| Shan || 13|| green\tblue || Sep. 27, 2009 ||
|| John || 45|| orange || Sep. 29, 2009 ||
|| Minna || 27|| teal || Sep. 30, 2009 ||
```

**Pull request merged**
